



import Head from 'next/head'

import styles from '../styles/index.module.css'

import 'bootstrap/dist/css/bootstrap.css'; // Add this line


import SearchDatabase from '../components/SearchDatabase'

import { useRouter } from 'next/router'


export default function Index(){
    const router = useRouter()

    return(
      
      <div className={styles["main-container"]}>
        <div>
          <Head>
            <title>Workshop Attendance</title>
          </Head>
        </div>
      
        <div className={styles["thebox"]}>
          <div className="text-center">
            <form className ="form-signin" id='submit-form'  onSubmit={async (e) => {
              e.preventDefault()
              const form = document.getElementById('submit-form')
              console.log(form.email.value) 
              if(form.email.value === ''){
                alert('Please enter your registered mail id')
                return
              }

              const searchResult = await SearchDatabase(form.email.value)
              if(searchResult ===  null){
                alert('This email was used to register for this workshop. Please enter the correct email.')
                return
              }
              router.push({ pathname: './user', query:{id : searchResult.id}}, '/user')

            }}>
              <img className="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72"/>
              <h1 className="h3 mb-3 font-weight-normal">Please sign in</h1>
              <label htmlFor="inputEmail" className="h6 sr-only"> Registered Email address </label>
              
             
              <input type="email" id="inputEmail" className="form-control" placeholder="Email address" name="email" required autoFocus  />
              <br/>
              
            
              <button className="btn btn-lg btn-primary btn-block" type="submit">Enter</button>
      
            </form>
          </div>
        </div>
  
      </div>
    )
  
  
  }



/*import Home from '../components/Home'
import styles from '../styles/index.module.css'




export default function Index(){

  
  return(

      <div className={styles["main-container"]}>
        <Home/>
      
      </div>
        
    )


}
*/
/*
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
*/